florian_demo_homepage:
    path:     /hello/{name}
    defaults: { _controller: florianDemoBundle:Default:index }    

florianUserBundle_user:
    resource: "@florianUserBundle/Resources/config/routing/user.yml"
    prefix:   /user
        
florianDemoBundle_post:
    resource: "@florianDemoBundle/Resources/config/routing/post.yml"
    prefix:   /post  
