parameters:
#    florian_demo.example.class: florian\DemoBundle\Example

services:
#    florian_demo.example:
#        class: %florian_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
