<?php

namespace florian\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findAllLimit() {
        $qb = $this->createQueryBuilder('a');
        $qb->orderby('a.id', 'ASC')->setMaxResults(200);
        return $qb->getQuery()->getResult();
    }

    
}
