florian_comment_homepage:
    path:     /hello/{name}
    defaults: { _controller: florianCommentBundle:Default:index }
    
fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }